---
# vars file for check_config_mode
prouter_name: "{{playbook_input.device_fqname[-1]}}"
prouter_fqname: "{{playbook_input.device_fqname}}"
prouter_vendor: "{{playbook_input.vendor | lower}}"
prouter_family: "{{playbook_input.device_family | lower}}"
username: "{{playbook_input.device_username}}"
password: "{{playbook_input.device_password}}"
