---
# tasks file for check_credentials
     - name: check credentials
       ssh_connection:
          hosts: "{{ host_vendor_mapping }}"
          credentials: "{{ credentials }}"
       register: successful_connections

     #- debug:
     #     msg: "{{ item.hostname }}  {{ item.username }} {{ item.password }}"
     #  with_items: "{{ successful_connections.ssh_success }}"

     - name: list
       vnc_db_mod:
         object_type: "physical_router"
         object_op: "list"
         object_dict: |
           {
              "filters": {"physical_router_management_ip":"{{ item.hostname }}"}
           }
         auth_token: "{{ auth_token }}"
       with_items: "{{ successful_connections.ssh_success }}"
       register: PR_url
       no_log: True

     # - debug:
     #      msg: "{{ item[0].obj['physical-routers'][0].uuid }} {{ item.1.hostname }}  {{ item.1.username }} {{ item.1.password }}"
     #   with_together:
     #       - "{{ PR_url.results }}"
     #       - "{{ successful_connections.ssh_success }}"


     - name: call vnc to update physical-router
       vnc_db_mod:
         object_type: "physical_router"
         object_op: "update"
         object_dict: |
          {
              "uuid": "{{ item[0].obj['physical-routers'][0].uuid }}",
              "physical_router_user_credentials": {
                  "username": "{{ item.1.username }}",
                  "password": "{{ item.1.password }}"
                  }
          }
         auth_token: "{{ auth_token }}"
       register: physical_router_uuids
       when: physical_router_uuids.failure == false
       with_together:
           - "{{ PR_url.results }}"
           - "{{ successful_connections.ssh_success }}"
       no_log: True

     - name: if vnc failed end play
       include_tasks: error_handler.yaml
       when: "physical_router_uuids.failure == true"
       vars:
         op_err_message: "{{ physical_router_uuids.msg }}"
         results: ""
         jl_err_message: "VNC error while creating PR Router " + "{{ physical_router_uuids.msg }}"