---
# tasks file for check_credentials
     - name: check credentials
       ssh_connection:
          hosts: "{{ host_vendor_mapping }}"
          credentials: "{{ credentials }}"
       register: successful_connections

     - name: list
       vnc_db_mod:
         job_ctx: "{{ job_ctx }}"
         object_type: "physical_router"
         object_op: "list"
         object_dict: |
           {
             "filters": {"physical_router_management_ip":"{{ item.hostname }}"}
           }
       with_items: "{{ successful_connections.ssh_success }}"
       register: PR_url

     - name: call vnc to update physical-router
       vnc_db_mod:
         job_ctx: "{{ job_ctx }}"
         api_server_host: "{{ api_server_host }}"
         object_type: "physical_router"
         object_op: "update"
         object_dict: |
           {
             "uuid": "{{ item[0].obj['physical-routers'][0].uuid }}",
             "physical_router_user_credentials": {
               "username": "{{ item.1.username }}",
               "password": "{{ item.1.password }}"
             }
           }
       register: physical_router_uuids
       with_together:
         - "{{ PR_url.results }}"
         - "{{ successful_connections.ssh_success }}"

     - debug: var=physical_router_uuids
