---

- name: "Read configuration type and filter"
  set_fact:
    mac_address: "{{input_params.get('mac_details').get('mac_address', '') | trim}}"

- name: "Print MAC value"
  debug:
    var: mac_address

- name: Getting output from device ... please wait
  block:
    - import_role:
        name: Juniper.junos

    - name: Execute commands on a Juniper Device to get info (current)...
      juniper_junos_command:
        commands:
          - "show evpn database extensive mac-address {{mac_address}}"
        display: text
        provider:
          host: "{{device_management_ip}}"
          username: "{{device_username}}"
          password: "{{device_password}}"
          port: 22
          timeout: "{{JUNOS_COMMAND_TIMEOUT|int}}"
      register: command_resp

    - name: "Print unmodified result"
      debug:
        var: command_resp

    - set_fact:
       format_resp: "{{command_resp.stdout }}"
    - set_fact:
       command_resp: "{{ format_resp | replace('\n', '\\r\\n') }}"
    - name: "Print modified result"
      debug:
        var: command_resp
