---
# tasks file for discover_role

- set_fact:
    job_ctx: "{{job_ctx|combine(percent_init_dict)}}"

- name: Start discovering roles for prouters in the fabric
  set_fact:
    role_discovery_result: "{{ job_ctx | discover_role(prouter_name, prouter_uuid, prouter_vendor_name, prouter_product_name) }}"

- name: check failure
  include_tasks: error_handler.yml
  when: role_discovery_result.status == 'failure'
  vars:
    op_err_message: "Unable to discover role due to error: {{ role_discovery_result.error_msg }}"
    jl_err_message: "Failed to discover roles due to error. Here is role_discovery log: {{ role_discovery_result.role_discovery_log }}"
    results:
      prouter_fqname: "{{ prouter_fqname }}"

- name: Update job log with percentage
  include_tasks: percentage_update.yml
  vars:
    current_index: 1
    jl_message: "Assigned {{ prouter_name }} with node profiles:\n   - {{ role_discovery_result.np_refs|join('\n   - ') }}"
    jl_details: {"assigned_node_profiles": "{{role_discovery_result.np_refs}}" }

