---
# vendor agnostic tasks file for check_config_mode

- set_fact:
    job_ctx: "{{job_ctx|combine(percent_init_dict)}}"

- name: Encapsulate all the operations in a block rescue for error handling
  block:
    - name: check to see if the ansible file for the vendor and family exists
      stat:
        path: "{{role_path}}/tasks/{{prouter_vendor}}_{{prouter_family}}.yml"
      register: p

    - name: Execute commands on device
      block:
        - include_tasks: "{{prouter_vendor}}_{{prouter_family}}.yml"
      when: p.stat.exists == True

    - name: check to see if the ansible file for the vendor exists
      stat:
        path: "{{role_path}}/tasks/{{prouter_vendor}}.yml"
      register: p_default

    - name: Execute commands on device
      block:
        - include_tasks: "{{prouter_vendor}}.yml"
      when: p_default.stat.exists == True

    - name: Calculate retries based on JUNOS_COMMIT_TIMEOUT value
      set_fact:
        retry_no: "{{(JUNOS_COMMIT_TIMEOUT/30) | int}}"

    - name: Invoke the retry logic for "{{30*retry_no}}" sec when the command has failed
      include_tasks: "do_until_loop.yml"
      vars:
        count: 1
        retries: "{{retry_no}}"
        delay: 30
      when: "'failed' in execute_command_resp and execute_command_resp.failed == true"

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Config mode check complete ... "

  rescue:
    - name: Perform the necessary error handling while trying to execute command possibly due to a retry timeout
      include_tasks: error_handler.yml
      when: "'failed' in execute_command_resp and execute_command_resp.failed == true"
      vars:
        op_err_message: "Error while trying to check config mode on {{prouter_vendor}} device, {{prouter_name}}: {{execute_command_resp.msg}}"
        jl_err_message: "Error while trying to check config mode on {{prouter_vendor}} device, {{prouter_name}}: {{execute_command_resp.msg}}"

    # this is when the playbook has to end for other unhandled failures
    - meta: end_play
