# Timeout settings for Ansible junos modules
JUNOS_COMMIT_TIMEOUT: 600
JUNOS_FACTS_TIMEOUT: 120
JUNOS_COMMAND_TIMEOUT: 120

# Device states for prouter object log
DEVICE_STATE:
  DISCOVERED: "DISCOVERED"
  ONBOARDED: "ONBOARDED"
  UNDERLAY_CONFIGURED: "UNDERLAY_CONFIGURED"
  IMAGE_UPGRADED: "IMAGE_UPGRADED"

JOBLOG_STATUS:
  IN_PROGRESS: "IN_PROGRESS"

# Job context to be passed to ansible modules
job_ctx:
  job_template_fqname: "{{ playbook_input.job_template_fqname }}"
  job_execution_id: "{{ playbook_input.job_execution_id }}"
  fabric_fqname: "{{ playbook_input.fabric_fq_name }}"
  config_args: "{{ playbook_input.args }}"
  job_input: "{{ playbook_input.input }}"
  auth_token: "{{ playbook_input.auth_token }}"
  playbook_job_percentage: "{{ playbook_input.playbook_job_percentage}}"
  # This is used in the job percentage calculations. Dataype is an int
  # Example: For the first task in image upgrade - dowloading the image
  # the current_task_index will be 1. Note: The first task index always needs
  # to be initialized from 1 and not 0
  current_task_index: 1
  # This is used in job percentage calculations. Dataype is int.
  # It is the total number of tasks in the playbook. For example,
  # image upgrade has four tasks (creates job logs 4 times)
  total_task_count: 1
  # This is used for job percentage calcualtions. Dataype is a array of int
  # For example for image upgrade it could be set to [5, 40, 45, 10]
  task_weightage_array:

#pool size
POOL_SIZE: 500

#Device Retry Timeout in Seconds
TOTAL_RETRY_TIMEOUT: 3600

#vendor mapping
vendor_mapping:
  - vendor: Juniper
    oid: 1.3.6.1.4.1.2636
  - vendor: Cisco
    oid: 1.3.6.1.4.1.9

#oid mapping for supported devices
device_family_info:
  - vendor: Juniper
    snmp_probe:
      - oid: 1.3.6.1.4.1.2636.1.1.1.4.82.8
        family: junos-qfx
        product: qfx5100
      - oid: 1.3.6.1.4.1.2636.1.1.1.4.82.5
        family: junos-qfx
        product: qfx5100
      - oid: 1.3.6.1.4.1.2636.1.1.1.4.82.10
        family: junos-qfx
        product: qfx10002
      - oid: 1.3.6.1.4.1.2636.1.1.1.2.29
        family: junos
        product: mx240
      - oid: 1.3.6.1.4.1.2636.1.1.1.2.11
        family: junos
        product: m10i
      - oid: 1.3.6.1.4.1.2636.1.1.1.2.57
        family: junos
        product: mx80
    ssh_probe:
      - command: echo "show system information | display xml" | cli
        data_format: xml
      - command: show system information | display xml
        data_format: xml

# Paths for DHCP and TFTP config files
DHCPD_CONFIG_PATH: "/etc/dhcp/dhcpd.conf"
TFTP_BOOT_PATH: "/var/lib/docker/volumes/ironic_pxe/_data"

# DHCP and TFTP servers
DHCP_SERVER: "localhost"
TFTP_SERVER: "localhost"

# MARKERS
JOB_PROGRESS_MARKER: "JOB_PROGRESS##"