---
- name: Delete all the devices in the fabric
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Include global variables
      include_vars: group_vars/all.yml

    - set_fact:
        job_ctx: "{{job_ctx|combine({'total_task_count':2, 'task_weightage_array':[10, 90] })}}"

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Deleting specified devices from fabric"

    - name: Delete devices in the fabric
      set_fact:
        output: "{{ job_ctx | delete_devices }}"

    - block:
        - set_fact:
            op_err_message: "Failed to delete fabric devices due to error: {{ output.error_msg }}. Here is the deletion log: {{ output.deletion_log }}"
            jl_err_message: "\nFail to delete device: {{ output.error_msg }}"
            results: {}

        - name: handle failure
          include_tasks: error_handler.yml
      when: output.status == 'failure'

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 2
        jl_message: "Successfully deleted fabric devices"
