---

- name: Push Junos Config and Read Back Facts
  hosts: localhost
  connection: local
  vars:
    input: "{{ playbook_input.input }}"
    prouter_uuid: "{{ playbook_input.device_id}}"
    output: {"status":"", "message":"", "results":""}
    as_numbers: []

  roles:
    - Juniper.junos
    - junos_read_prouter
    - junos_underlay_common
    - commit_config
    - contrail_create_bgp_router

  tasks:
    - set_fact:
        output: {
              "status": "Success",
              "message": "Underlay config successful for: {{junos_host}}"
          }

    - name: print output
      debug: var=output verbosity=1
