- name: Image Upgrade
  hosts: localhost
  gather_facts: no
  connection: local

  roles:
    - Juniper.junos
    - image_upgrade_role

  tasks:
    - set_fact:
        output: {
              "status": "Success",
              "message": "Image upgrade for device: {{pr_name}} {{prouter_uuid}} successful",
              "results":
                  {
                    "prouter_uuid": "{{prouter_uuid}}",
                    "image_uuid": "{{image_uuid}}",
                    "msg": "Device {{pr_name}} is upgraded with image: {{filename}}"
                  }
          }

    - name: Print the output.
      debug:
        var: output
        verbosity: 1

    - set_fact:
        line: "{{job_ctx.unique_pb_id}} END"

    - name: insert/update in /tmp/<exec-id> file
      set_fact:
        write_resp: "{{job_ctx.job_execution_id | write_to_file(line)}}"
