---
- name: Assign physical or overlay roles to the devices in the fabric
  hosts: localhost
  connection: local
  tasks:
    - set_fact:
        job_ctx: "{{job_ctx|combine({'total_task_count':2, 'task_weightage_array':[10, 90] })}}"

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Assigning physical/overlay roles to the devices in the fabric"

    - name: assign roles to the devices
      set_fact:
        output: "{{ job_ctx | assign_roles(supported_roles) }}"

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      when: output.status == 'failure'
      vars:
        current_index: 1
        jl_message: "Failed to assign roles due to error: {{ output.error_msg }}"

    - pause: seconds=5
      when: output.status == 'failure'

    - name: check failure
      include_tasks: error_handler.yml
      when: output.status == 'failure'
      vars:
        op_err_message: "Unable to assign roles to devices due to error"
        jl_err_message: "Failed to assign roles to devices due to error: {{ output.error_msg }}"
        results: {}

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 2
        jl_message: "Successfully assigned roles to devices"