---
- name: Assign physical or overlay roles to the devices in the fabric
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Include global variables
      include_vars: group_vars/all.yml

    - set_fact:
        job_ctx: "{{job_ctx|combine({'total_task_count':2, 'task_weightage_array':[10, 90] })}}"

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Assigning physical/overlay roles to the devices in the fabric"

    - name: assign roles to the devices
      set_fact:
        output: "{{ job_ctx | assign_roles }}"

    - block:
        - set_fact:
            op_err_message: "{{ output.error_msg }}. Here is the assignment log: {{ output.assignment_log }}"
            jl_err_message: "\nFailed to assign roles: {{ output.error_msg }}"
            results: {}

        - name: handle failure
          include_tasks: error_handler.yml
      when: output.status == 'failure'

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 2
        jl_message: "Successfully assigned roles to devices"