---
- name: Import Servers from File
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - set_fact:
        job_ctx: "{{job_ctx|combine({'total_task_count':1, 'task_weightage_array':[100] })}}"
    - debug: var=playbook_input
    - set_fact:
        output: "{{ playbook_input | import_nodes_from_file }}"
    - debug:
        msg: "OUTPUT {{ output }}"
    - debug:
        msg: "SERVER IMPORT  {{ output.added_nodes }}"

    - block:
        - set_fact:
          op_err_message: "Failed to discover server due to error: {{ output.error_msg }}. Here is the fabric onboard log: {{ output.discover_log}}"
          jl_err_message: "Failed to discover server due to error: {{ output.error_msg }}"
          results: {}
        - name: Update job log with percentage
          include_tasks: percentage_update.yml
          vars:
            current_index: 1
            jl_message: "{{ jl_err_message }}"

        - pause: seconds=5

        - name: handle failure
          include_tasks: error_handler.yml
      when: output.status == 'failure'

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Successfully added nodes to CC '{{ output.added_nodes }}'"
