---
- name: Import Servers from File
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Include global variables
      include_vars: group_vars/all.yml

    - name: Update job_ctx
      set_fact:
        job_ctx: "{{job_ctx|combine({'total_task_count':1, 'task_weightage_array':[100] })}}"
    - debug: var=playbook_input verbosity=2
    - name: Importing servers
      set_fact:
        output: "{{ playbook_input | import_nodes_from_file }}"
    - debug:
        msg: "OUTPUT {{ output }}"
        verbosity: 2

    - block:
        - name: Define variables for failed import
          set_fact:
            op_err_message: "Failed to import server due to error: {{ output.error_msg }}. Here is the fabric onboard log: {{ output.import_log}}"
            jl_err_message: "Failed to import server due to error: {{ output.error_msg }}"
            results: {}
        - name: Update job log with percentage
          include_tasks: percentage_update.yml
          vars:
            current_index: 1
            jl_message: "{{ jl_err_message }}"

        - pause: seconds=5

        - name: handle failure
          include_tasks: error_handler.yml
      when: output.status == 'failure'

    - debug:
        msg: "SERVER IMPORT  {{ output.added_nodes }}"
        verbosity: 2
      when: output.status == 'success'

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Successfully added nodes to CC '{{ output.added_nodes }}'"
