---
- name: Get the Topology Information from this device

  hosts: localhost
  connection: local

  roles:
    - Juniper.junos
    - topology_discovery_role

  tasks:

    - set_fact:
        output: "{{output }}"

