---
- name: Update the DHCP config
  hosts: localhost
  connection: local
  gather_facts: no

  pre_tasks:
    - set_fact:
        percent_init_dict: { 'total_task_count': 2, 'task_weightage_array': [50, 50] }
    - name: Save fabric UUID
      set_fact:
        fabric_uuid: "{{ playbook_input.input.fabric_uuid }}"

  tasks:
    - name: Get fabric fq_name
      vnc_db_mod:
        enable_job_ctx: False
        job_ctx: "{{ job_ctx }}"
        object_type: "fabric"
        object_op: "id_to_fq_name"
        object_dict: |
          {
            "uuid": "{{ fabric_uuid }}"
          }
      register: fabric_fq_name
    - name: Save fabric name
      set_fact:
        fabric_name: "{{ fabric_fq_name.fq_name[-1] }}"
    - set_fact:
        ztp_create: True
        only_restart: True

    - import_role:
        name: ztp_dhcp_config
    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Generated DHCP config for fabric {{fabric_name}}"
    - import_role:
        name: ztp_dhcp
    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 2
        jl_message: "Updated DHCP config for fabric {{fabric}}"
      when: dhcp_output is undefined
    - name: If error, set output and bail
      set_fact:
        output: "{{dhcp_output}}"
      when: dhcp_output is defined
    - name: Set output message
      set_fact:
        output: {'status':'Success', 'message':'Updated DHCP config'}
      when: output is undefined
