- import_role:
    name: Juniper.junos

- name: Check manual commits
  include_role:
    name: rollback_compare
  ignore_errors: True
  static: no

- name: Check SSH connectivity
  wait_for:
    host: "{{prouter_dynamic_ip}}"
    port: 22
    timeout: 300
    connect_timeout: 10
    sleep: 5

- name: Execute commands on a Juniper Device to get system info
  juniper_junos_command:
    commands:
      - show system information
    display: xml
    provider:
      host: "{{prouter_dynamic_ip}}"
      username: "{{username}}"
      password: "{{password}}"
      port: 22
      timeout: "{{timeout}}"
  register: show_system_resp

- name: Extract hardware model
  set_fact:
    device_hardware_model: "{{show_system_resp|json_query('parsed_output.\"system-information\".\"hardware-model\"')}}"

- name: Extract OS version
  set_fact:
    device_os_version: "{{show_system_resp|json_query('parsed_output.\"system-information\".\"os-version\"')}}"

- name: Update the prouter object with the os version
  vnc_db_mod:
    job_ctx: "{{ job_ctx }}"
    object_type: "physical_router"
    object_op: "update"
    object_dict: |
      {
       "uuid": "{{prouter_uuid}}",
       "physical_router_os_version": "{{device_os_version}}"
      }
  register: prouter_obj

