---
# vars file for import_device_facts
prouter_name: "{{playbook_input.device_fqname[-1]}}"
prouter_fqname: "{{playbook_input.device_fqname}}"
prouter_vendor: "{{playbook_input.vendor | lower}}"
prouter_family: "{{playbook_input.device_family | lower}}"
username: "{{playbook_input.device_username}}"
host: "{{playbook_input.device_management_ip}}"
password: "{{playbook_input.device_password}}"
timeout: "{{DEVICE_FACTS_TIMEOUT|int}}"
schema_file: "{{playbook_dir}}/schema/import_device_facts_schema.json"