---
prouter_name: "{{playbook_input.device_fqname[-1]}}"
prouter_vendor: "{{playbook_input.vendor | lower}}"
prouter_family: "{{playbook_input.device_family | lower}}"
dynamic_mgmt_ip: "{{playbook_input.input.dynamic_mgmt_ip}}"
prouter_mgmt_ip: "{{playbook_input.device_management_ip}}"
username: "{{playbook_input.device_username}}"
password: "{{playbook_input.device_password}}"
timeout: "{{DEVICE_COMMAND_TIMEOUT | int}}"
