---
# defaults file for import_device_facts
percent_init_dict: { 'total_task_count':3, 'task_weightage_array':[30, 50, 20] }
execute_command_resp: {}
device_info: {}
parser_output: {}
device_facts_payload: {}
schema_validation_resp: {}