---
# vars file for import_lldp_info
prouter_name: "{{playbook_input.device_fqname[-1]}}"
prouter_fqname: "{{playbook_input.device_fqname}}"
prouter_vendor: "{{playbook_input.vendor | lower}}"
prouter_family: "{{playbook_input.device_family | lower}}"
username: "{{playbook_input.device_username}}"
host: "{{playbook_input.device_management_ip}}"
password: "{{playbook_input.device_password}}"
timeout: "{{DEVICE_COMMAND_TIMEOUT | int}}"
schema_file: "{{playbook_dir}}/schema/import_lldp_info_schema.json"
delay: 5
count: 0
retries: 3