- name: Get swift download url for the image
  swift_fileutil:
    authtoken: "{{auth_token}}"
    authurl: "{{auth_url}}"
    user: "{{user}}"
    key: "{{key}}"
    tenant_name: "{{tenant_name}}"
    auth_version: "{{auth_version}}"
    temp_url_key: "{{temp_url_key}}"
    temp_url_key_2: "{{temp_url_key_2}}"
    chosen_temp_url_key: "{{chosen_temp_url_key}}"
    container_name: "{{container_name}}"
    filename: "{{filename}}"
  register: swift_results

- name: Print the complete response.
  debug:
    var: swift_results
    verbosity: 1

# handle error/exception from swift and set output
- name: Fail if swift module returned error
  include_tasks: error_handler.yml
  when: "swift_results.error_msg != None and swift_results.error_msg != ''"
  vars:
    op_err_message: "Unable to get image file url from Swift. {{swift_results.error_msg}}"
    results: |
      {
        "prouter_uuid": "{{prouter_uuid}}",
        "image_uuid": "{{image_uuid}}",
        "msg": "Unable to get image file url from Swift."
      }
    jl_err_message: "Upgrade device {{pr_fqname}}, Image name: {{filename}}. Unable to get image file url from Swift. {{swift_results.error_msg}}"

- set_fact:
    downloadurl: "{{swift_results.url}}"
