---
# defaults file for check_config_mode

percent_init_dict: { 'total_task_count':1, 'task_weightage_array':[100] }
output: {
              "status": "Success",
              "message": "Config mode check successful"
        }
execute_command_resp: {}
device_info: {}
retry_no: 20