---
    - name: Generate Base common config
      block:
        - template:
            src: junos.common.conf.j2
            dest: "{{ conf_dir }}/build_config/common_config.conf"
          register: cmd_res
        - debug: var=cmd_res verbosity=1
      rescue:
        - set_fact:
            output: {
              "status": "Failed to Generate config",
              "message": "{{cmd_res.msg}}"
            }

        - debug: var=output verbosity=1

        - name: Appending job log for reading necessary info from database
          job_objectlog:
            job_ctx: "{{ job_ctx }}"
            message: "Failed to generate configuration 'common_config':\n{{ cmd_res.msg }}"
            status: "{{ JOBLOG_STATUS.IN_PROGRESS }}"

        - meta: end_play
