- set_fact:
    logical_unit: "{{item}}"

- set_fact:
    log_interface_name: "{{logical_unit.name|replace(':', '_')}}"

- set_fact:
    payload: {"parent_type": "physical-interface",
              "fq_name": ["default-global-system-config", "{{prouter_name}}", "{{phy_interface_name}}", "{{log_interface_name}}"],
              "display_name": "{{logical_unit.name}}"
             }

- name: create the adress_family for runtime log interface
  include_tasks: log_interface_address_family.yaml
  when: "'address-family' in logical_unit"

- name: create the log interface
  include_tasks: log_interface.yaml
