---
- name: Onboard fabric data model to the database

  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    feature: basic
  tasks:
    - set_fact:
        additional_feature_params: {
          "basic": {
            "ntp": {
              "time_zone": "Los Angeles",
              "ntp_servers": ["2.2.2.2", "3.3.3.3"],
              "ntp_boot_servers": ["2.2.2.2", "4.3.3.3"]
            },
            "name_servers": ["10.1.1.2", "11.1.1.2"],
            "domain_name": "company.net",
            "host_name": "mx-480t",
            "snmp": {
              "communities": [
                { "name": "public", "readonly": true }
              ]
            },
            "static_routes": [
              {
                "subnets": ["192.168.1.0/24", "192.168.2.0/24"],
                "nexthop": "192.168.1.1"
              }
            ]
          }
        }

    - template:
        src: juniper_basic.j2
        dest: /tmp/output.json

    - command: cat /tmp/output.json
      register: output

    - debug: var=output.stdout_lines
