- name: get device info
  discover_device:
    fabric_uuid: "{{ fabric_uuid }}"
    job_ctx: "{{ job_ctx }}"
    subnets: "{{ host_prefix }}"
    version: "v2c"
    community: "public"
    device_family_info: "{{ device_family_info }}"
    vendor_mapping: "{{ vendor_mapping }}"
    pool_size: "{{ POOL_SIZE }}"
    total_retry_timeout: 0
  register: discovery_results
