---
# defaults file for device-import-role
configured_phy_interface_names: []
output: {
              "status": "Success",
              "message": "Device Import for device: {{prouter_name}} successful"
        }
upd_dataplane_ip_mesg: ""
