---
# defaults file for device_facts_uve
percent_init_dict: { 'total_task_count':2, 'task_weightage_array':[30, 70] }
execute_command_resp: {}
device_info: {}
parser_output: {}
device_facts_payload: {}
schema_validation_resp: {}