---
- name: Onboard fabric data model to the database

  hosts: localhost
  connection: local

  vars:
    feature: lag
  tasks:
    - set_fact:
        device_abstract_config: {
          "comment": "/* Contrail Generated Group Config */",
          "bgp": [{
            "comment": "ip_clos",
            "peers": [{
              "comment": "ip_clos",
              "ip_address": "20.1.1.251",
              "autonomous_system": 64000
            }],
            "ip_address": "20.1.1.252",
            "autonomous_system": 64001
          }],
          "physical_interfaces": [{
            "comment": "ip_clos",
            "logical_interfaces": [{
              "comment": "ip_clos",
              "uuid": "8a99b692-9216-4db6-aeb2-a09ae5344845",
              "name": "et-0/0/32.0",
              "unit": 0,
              "ip_list": [{
                "address": "30.1.1.2"
              }]
            }],
            "name": "ae0",
            "interface_type": "lag",
            "link_aggregation_group": {
              "comment": "lag",
              "lacp_enabled": True,
              "link_members": ["et-0/0/31.0","et-0/0/32"]
              },
            "uuid": "787af41c-b4fb-41fb-abd5-53553e0f198c"
          }, {
            "comment": "ip_clos",
            "logical_interfaces": [{
              "comment": "ip_clos",
              "uuid": "a6db1977-9061-4368-b1a2-f380600d9106",
              "name": "et-0/0/33.0",
              "unit": 0,
              "ip_list": [{
                "address": "30.1.1.6"
              }]
            }],
            "name": "et-0/0/33",
            "uuid": "73556900-64cf-4330-8270-93b9facb0514"
          }, {
            "comment": "ip_clos",
            "logical_interfaces": [{
              "comment": "ip_clos",
              "uuid": "32c4f38b-ae59-4822-a883-fd5a69f1c465",
              "name": "lo0.0",
              "unit": 0,
              "ip_list": [{
                "address": "20.1.1.252"
              }]
            }],
            "name": "lo0",
            "uuid": "e6d5d7a4-5223-4fb7-9a3b-fbbeb2240846"
          }],
          "system": {
            "loopback_ip_list": [{
              "address": "20.1.1.252"
            }],
            "name": "DK588",
            "device_family": "junos-qfx",
            "management_ip": "192.168.10.3",
            "credentials": {
               "authentication_method": "PasswordBasedAuthentication",
              "password": "Embe1mpls",
              "user_name": "root"
            },
            "vendor_name": "Juniper",
            "product_name": "qfx10002-36q",
            "uuid": "2956c26f-8a56-48a2-a12c-2eeb4a653edf"
          }
        }
    - debug: var=device_abstract_config

    - template:
        src: juniper_junos-qfx_lag.j2
        dest: /tmp/output1.json

    - command: cat /tmp/output1.json
      register: output

    - debug: var=output.stdout_lines
