---
    - name: Pushing config ... please wait
      block:
        - import_role:
            name: Juniper.junos

        - juniper_junos_config:
            load: "{{ load }}"
            lines: "{{ device_config }}"
            comment: "Contrail execution ID: {{ job_ctx.job_execution_id }}"
            ignore_warning: "True"
            format: "{{ format }}"
            config_mode: private
            provider:
              host: "{{ host }}"
              username: "{{ username }}"
              password: "{{ password }}"
              port: 22
              timeout: "{{ timeout }}"
          register: junos_response
        - set_fact:
           device_push_response: "{{ junos_response }}"
        - set_fact:
           device_push_message: >
               {% if 'diff_lines' in junos_response -%}
                  Junos config push response for device '{{ prouter_name }}' \n{{ junos_response.msg }} \nDiff: {{ junos_response.diff_lines }}
               {% else -%}
                  Junos config push response for device '{{ prouter_name }}' \n{{ junos_response.msg }} \nDiff: "No config change, nothing to deploy"
               {%- endif %}
      rescue:
        - include_tasks: error_handler.yml
          vars:
            op_err_message: "Unable to push config on the device, Junos config push task failed with following error:\n{{ junos_response.msg }}"
            results: |
              {
                "device_name": "{{ prouter_name }}",
                "msg": "Junos config push task failed"
              }
            jl_err_message: "Unable to push config on the device, Junos config push task failed with following error:\n{{ junos_response.msg }}"
          when: prouter_mgmt_ip == prouter_dynamic_ip