device_mgmt_ip: "{{pr_host}}"
device_vendor: "{{pr_vendor | lower}}"
device_fqname: "{{pr_fqname}}"
device_name: "{{playbook_input.device_fqname[-1]}}"
device_username: "{{pr_user}}"
device_uuid: "{{pr_uuid}}"
device_password: "{{pr_password}}"
is_hitless_upgrade: "{{playbook_input.device_hitless_upgrade}}"
advanced_parameters: "{{playbook_input.input.advanced_parameters}}"
upgrade_plan: "{{playbook_input.input.upgrade_plan}}"
additional_error_handler: "hitless_upgrade_errors.yml"
abort_upon_failure: "{{advanced_parameters.health_check_abort}}"
lacp_down_peer_check: "{{advanced_parameters.Juniper.lacp.lacp_down_peer_check}}"
lacp_down_local_check: "{{advanced_parameters.Juniper.lacp.lacp_down_local_check}}"

