---
# defaults file for topology_discovery_role

percent_init_dict: {'current_task_index':1, 'total_task_count':4, 'task_weightage_array':[32, 32, 32, 4] }
output: {
              "status": "Success",
              "message": "Topology discovery for device: {{prouter_name}} successful",
              "results": []
        }
